Add echo when reusing old modulefiles

diff --git a/container-mod b/container-mod
--- a/container-mod
+++ b/container-mod
@@ -427,6 +427,7 @@ pull() {
     singularity pull --force "$target_image_path" "$uri" || exit 1
     chmod 755 "$target_image_path"
     echo "   Pull complete."
+    echo "Container image is pulled into: $target_image_path"
 }
 
 # Generates an Lmod modulefile for a container.
@@ -478,8 +479,10 @@ print_modulefile() {
 
     if [[ -z "$latest_modulefile" ]];
     then
+        echo "No existing modulefile found for $app. Generating a new one."
         generate_new_modulefile "$uri"
     else
+        echo "Found existing modulefile: $latest_modulefile, will repurpose it for $uri."
         repurpose_old_modulefile "$uri" "$latest_modulefile"
     fi
     return $?
@@ -674,11 +677,11 @@ exec() {
             warn -p "     -> Warning: Executable not found in container: $command_exec"
         fi
     done
-    chmod -R 755 "$AppTool_dir" || {
-            warn -p "Error: Failed to set permissions for directory $AppTool_dir"
+    chmod -R 755 "${exec_outdir}/${app}" || {
+            warn -p "Error: Failed to set permissions for directory ${exec_outdir}/${app}"
             return 1
         }
-    echo "   Executables generated in: $AppTool_dir"
+    echo "   Executables generated in: ${exec_outdir}/${app}"
 }
 
 # Checks if a given command exists inside the container.
